usuario_login:
    path: /admin
    defaults: { _controller: UsuarioBundle:Default:login }

usuario_login_check:
    path: /admin/login_check

usuario_logout:
   path: /admin/logout

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /admin

CoreBundle:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /admin
    
AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /admin
    
FrontBundle:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /
    
