FrontBundle_default:
    resource: "@FrontBundle/Resources/config/routing/default.yml"
    prefix:   /

AppBundle_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix:   /
    
AppBundle_vehiculo:
    resource: "@AppBundle/Resources/config/routing/vehiculo.yml"
    prefix:   /vehiculo

AppBundle_categoria:
    resource: "@AppBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

AppBundle_compania:
    resource: "@AppBundle/Resources/config/routing/compania.yml"
    prefix:   /compania