<?php

namespace APP\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends EntityRepository {

    
     public function vehiculosPublicados() {

        $qb = $this->createQueryBuilder('v');


        $qb->where("v.estado = :en_venta")
                ->setParameter('en_venta', Vehiculo::en_venta);

        $qb->andWhere("v.publicado = :publicado")
                ->setParameter('publicado', Vehiculo::publicado);
  
        return $qb->getQuery()->getResult();
    }
    

}
